apiVersion: apps/v1
kind: Deployment
metadata:
  name: feedback-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: feedback-backend
  template:
    metadata:
      labels:
        app: feedback-backend
    spec:
      containers:
        - name: backend
          image: roobobo/feedback-backend:latest
          ports:
            - containerPort: 3001
          env:
            - name: MONGO_URL
              value: "mongodb://mongo:27017/feedbackDB"
